# Generated by Django 4.1.7 on 2023-12-12 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetable', '0002_class_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('start_rollno', models.IntegerField()),
                ('end_rollno', models.IntegerField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.class')),
            ],
        ),
    ]
