# Generated by Django 4.1.7 on 2023-12-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rollno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
