# Generated by Django 4.1.7 on 2023-12-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='capacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
